### ISSUE TITLE
Create a responsive navbar with buttons

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#13]
Add images after you complete-

**Comment by STM3900** [comment]
Hello, i want to work on this! can you asign me ?

**Comment by Akshay9607** [comment]
hello , can i work on this issue please ?

**Comment by abhishek213-alb** [comment]
@STM3900 @Akshay9607 hey can you work with #16  #15 
select anyone

**Comment by Abhishekvermaa** [comment]
can you assign this issue to me ?

**Comment by rohinirai010** [comment]
Hey can you please assign this issue to me, as I have already designed a whole website so I know how to do this.

**Comment by abhishek213-alb** [comment]
sure @rohinirai010  can you try issue #21 too

**Comment by rohinirai010** [comment]
> sure @rohinirai010 can you try issue #21 too

yeah sure

**Comment by VidishaAG** [comment]
Can I work on this issue please?
