### ISSUE TITLE
Add designing on the cards of the music app

### ISSUE THREAD

**Issue by zugzwang03** [abhishek213-alb/CountdownTimer#139]
I want to add some border radius and box shadow in the cards of the music app.
Can I work on this issue under Hacktoberfest'22?

![music](https://user-images.githubusercontent.com/95460021/196037625-c3a55be5-845e-4132-add7-02971dd35fd3.png)

**Comment by guneshmunjal** [comment]
could you please assign me this issue sir

**Comment by guneshmunjal** [comment]
under hacktoberfest 2022

**Comment by zugzwang03** [comment]
Sorry @guneshmunjal , but I created this issue to get self-assigned 😢

**Comment by guneshmunjal** [comment]
could we work together and collaborate @zugzwang03

**Comment by zugzwang03** [comment]
@abhishek213-alb
