### ISSUE TITLE
Modify the header of the music app

### ISSUE THREAD

**Issue by zugzwang03** [abhishek213-alb/CountdownTimer#140]
I want to modify the header of the music app, like a separate transparent grey background for it, with a slightly higher font size, so that it catches the attention of the listener or the user easily. 
Also, I feel if the header stays at top irrespective of how much you scroll down the page, the user will stay updated with what is playing currently. Just a suggestion, do let me know your views :)
Can I work on this issue under Hacktoberfest'22?

![music](https://user-images.githubusercontent.com/95460021/196037725-3a31164b-11a3-48bc-9bb8-064e994d989b.png)

**Comment by guneshmunjal** [comment]
could you please assign me this issue under hactoberfest.
i would like to resolve this issue.

**Comment by zugzwang03** [comment]
@abhishek213-alb

**Comment by zugzwang03** [comment]
@abhishek213-alb
