### ISSUE TITLE
Create a home page

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#15]
Create a homepage with a hyperlink that redirects to a countdown application

**Comment by Cursed-Ninja** [comment]
Can you provide more information on what kind of homepage you need?

**Comment by abhishek213-alb** [comment]
Simple with animated sliders...

**Comment by Cursed-Ninja** [comment]
Didn't get it. What content do you want on the homepage? Just a link to redirect to countdown? Do you have any design sample?

**Comment by abhishek213-alb** [comment]
- A slider with animated images basically about time management /quotes 
- Hover Cards (Animated ) with 3 buttons out of which one will redirect to the timer .

No sample design you can use your own creativity

**Comment by Cursed-Ninja** [comment]
So basically, a carousel for time managements images/quotes. 
What about that "Hover cards" thing? What will it contain? Just one hovercard with three buttons out of which 2 are dummy placeholders and one will redirect?

**Comment by abhishek213-alb** [comment]
Yes

**Comment by abhishek213-alb** [comment]
3 hover cards with 3 buttons below it out of which one will redirect to timer page

**Comment by Cursed-Ninja** [comment]
Is it ok if I use unsplash images for generating random quote images? shttps://source.unsplash.com/800x450/?quote
Also kindly assign this issue to me.

**Comment by abhishek213-alb** [comment]
Yes you can
