### ISSUE TITLE
Style the navbar and add a search box

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#16]

**Comment by Akshay9607** [comment]
Hey , can i work on this issue please

**Comment by abhishek213-alb** [comment]
Yes go ahead

**Comment by Abhishekvermaa** [comment]
if someone is not working,pls assign this issue to me

**Comment by Abhishekvermaa** [comment]
navbar buttons are not responsive in the mobile version .

**Comment by Akshay9607** [comment]
Hey , i made the changes above mentioned 
Navbar on large screen : 
![navbar_lg](https://user-images.githubusercontent.com/114289275/194076458-15a35c95-39ba-4b13-9415-5cbb2497cae9.png)

Navbar on small screen :
![navbar-sm](https://user-images.githubusercontent.com/114289275/194076629-27d1df41-f379-4f62-b795-a8182242a24c.png)

if any changes required let me know

**Comment by abhishek213-alb** [comment]
Nice work . Could you try adding a gradient to the navbar color?

**Comment by abhishek213-alb** [comment]
@Akshay9607 no done
just click on contribute .>then open a pull request > create 
follow this sequence

**Comment by Akshay9607** [comment]
Hey , i made pull request but it saying merge conflict , due to one who designed home page has made different navbar ,
Now what should i need to do ?

**Comment by abhishek213-alb** [comment]
Change the navbar according to you & then create a pr

**Comment by Akshay9607** [comment]
hello , i changed the navbar according to home page designed , can you please review it and merge this
