### ISSUE TITLE
Create a online notepad 

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#167]
Create a online note with all features like zoom ,copy,cut ,share and zoom also.

**Comment by Sinon11901** [comment]
I would like to work on this issue. Can you assign me to this?

**Comment by abhishek213-alb** [comment]
@Sinon11901 sure go ahead

**Comment by abhishek213-alb** [comment]
Can you share a video demo too .

**Comment by Sinon11901** [comment]
https://github.com/user-attachments/assets/12e3bf6c-504a-4a90-8394-77640ba1ed30

**Comment by Sinon11901** [comment]
If you have some requests or comments I can improve it and make other changes.
