### ISSUE TITLE
Add Navbar to homepage

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#23]
Make sure it's responsive for all devices

**Comment by kiransatdive** [comment]
Can you give me this project and i work it ,I work on this project .

**Comment by AadeshKabra** [comment]
Hi, I would like to work on this.

**Comment by abhishek213-alb** [comment]
@kiransatdive assigned

**Comment by abhishek213-alb** [comment]
@AadeshKabra you can check other issues
