### ISSUE TITLE
Improve Cards 

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#24]
Add images to the card. Hovering over it should show a button to redirect to any link, like the last one redirects to a timer app.

Sample

![image](https://user-images.githubusercontent.com/76660005/193804925-1b2ce525-b9d3-4816-8c53-8fb2336825c5.png)
File

**Comment by Chaitanya-087** [comment]
hi! i would like to work on it

**Comment by abhishek213-alb** [comment]
Go ahead

**Comment by Chaitanya-087** [comment]
need info,
there are actually three cards, should i add the effect to all of them

**Comment by abhishek213-alb** [comment]
Yes in all but only last one will redirect to timer app
Other 2 won't

**Comment by Chaitanya-087** [comment]
done! sent a pr

**Comment by abhishek213-alb** [comment]
Great work
