### ISSUE TITLE
Better Sign Up Button

### ISSUE THREAD

**Issue by incognion** [abhishek213-alb/CountdownTimer#43]
Sign up button looks quite unattractive. I can do some CSS works to look it attractive.

Please assign it to me under Hacktoberfest 2022. Thank you.

**Comment by abhishek213-alb** [comment]
Assigned also add signup login form too

**Comment by manav-06** [comment]
Hi @abhishek213-alb , you can assign this to me

**Comment by Hardikaz** [comment]
Hi @abhishek213-alb , I am interested to work on this pls assign it to me

**Comment by abhishek213-alb** [comment]
@manav-06 @Hardikaz already assigned please check other issues
