### ISSUE TITLE
Responsive design 

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#5]
Can you make this website responsive for all types of devices?

**Comment by amisha24** [comment]
Hy can I work on this please

**Comment by abhishek213-alb** [comment]
@amisha24 Assigned go ahead

**Comment by amisha24** [comment]
Thank you

**Comment by amisha24** [comment]
Due to some reasons, i may not work on it sorry of inconvenience

**Comment by Ritika-Agrawal811** [comment]
Hey if this is issue is not assigned to anyone then may I work on it?

**Comment by abhishek213-alb** [comment]
Sure go ahead

**Comment by iamakhileshmishra** [comment]
Is this issue still open ? If it is then @abhishek213-alb  assign it to me i would love to work upon it

**Comment by abhishek213-alb** [comment]
@iamakhileshmishra you can try issue no #7 or #9

**Comment by iamakhileshmishra** [comment]
I have raised the issue under #7 please assign that to me.
