### ISSUE TITLE
There is no favicon on website

### ISSUE THREAD

**Issue by MohitNamdev22** [abhishek213-alb/CountdownTimer#51]
The website doesn't have a favicon, So can I use the logo and create a favicon and link it with the website?
![image](https://user-images.githubusercontent.com/89779447/194229420-7dcff96a-3305-4bf5-8d79-e73ba7b09ee6.png)

**Comment by Shreejan-35** [comment]
Can you get the credit if we clear the issue before any one else???

**Comment by MohitNamdev22** [comment]
> Can you get the credit if we clear the issue before any one else???

No because, it is assigned to me and I'm started working on it

**Comment by Shreejan-35** [comment]
OK Sure I will try to work on another issue
