### ISSUE TITLE
[Bug]: Dropdown menus in navbar not showing properly

### ISSUE THREAD

**Issue by zelfroster** [abhishek213-alb/CountdownTimer#52]
### Description
- When hovered dropdown menus show up, but not normally.
- Links are broken in dropdown menus. (Service and Plans)
### Screenshot
- Normal state
![1665046200_Oct06_14:20:00](https://user-images.githubusercontent.com/93514460/194267286-d31207f1-d28a-45e7-a383-5d73ae1c7c48.png)
- Hovered state
![1665046216_Oct06_14:20:16](https://user-images.githubusercontent.com/93514460/194267297-c731d311-8217-48f2-a7b1-481d0ca56f14.png)

**Comment by abhishek213-alb** [comment]
Go ahead
