### ISSUE TITLE
Add footer to the home page

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#60]
- Footer should contain all social media buttons
- use wavy animated background for footer

**Comment by Abhinav-3359** [comment]
which which social platform to add?

**Comment by abhishek213-alb** [comment]
facebook , insta, quora, linkdn , telegram , youtube

**Comment by abhishek213-alb** [comment]
Just add button and leave '#' for hyperlink
![image](https://user-images.githubusercontent.com/76660005/194399845-076e89f1-ff03-48ec-a206-a3f05353a989.png)
here is sample image for buttons

**Comment by Abhinav-3359** [comment]
Got it, thanks!

**Comment by Abhinav-3359** [comment]
Thanks a lot.
