### ISSUE TITLE
Adding functonality to set countdown timer on webpage

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#7]

**Comment by deven-533** [comment]
Hello, Please Assign this issue to me Sir.

**Comment by abhishek213-alb** [comment]
Assigned go ahead

**Comment by deven-533** [comment]
Sir, I want t clear a doubt regarding the issue,
do I need to add the date of neet 2023 or make it dynamic using a user input date?

**Comment by abhishek213-alb** [comment]
Hey make it dynamic one

**Comment by iamakhileshmishra** [comment]
Please assign this to me i would to contribute under this issue

**Comment by abhishek213-alb** [comment]
Assigned

**Comment by abhishek213-alb** [comment]
@deven-533 @iamakhileshmishra  also add images after running it on demos folder...

**Comment by iamakhileshmishra** [comment]
The current Home page is not well styled when I locally run it 
The tittle is getting overlapped by the timer in wide view
![image](https://user-images.githubusercontent.com/79476272/193514804-b8d1585b-b0a3-4d69-b3d1-b1b09833c812.png)

And working fine in normal view
![image](https://user-images.githubusercontent.com/79476272/193514892-1e0e499d-7a3b-4681-ac38-6aff41b72274.png)

I would like to start my contribution from fixing this bug could i proceed

**Comment by abhishek213-alb** [comment]
Yes go ahead

**Comment by iamakhileshmishra** [comment]
I have solved this bug please check and merge it so that i can proceed further with the next

**Comment by iamakhileshmishra** [comment]
I have added the custom Countdown set feature Please merge it under "hacktoberfest-accepted" so that I can work on other issues.
![image](https://user-images.githubusercontent.com/79476272/193660680-7772a0f1-b9bf-468f-acc4-de6d663e6430.png)

![image](https://user-images.githubusercontent.com/79476272/193660768-c09aa855-610c-4917-b6bd-8ed36c08ac93.png)

**Comment by abhishek213-alb** [comment]
excellent work -
