### ISSUE TITLE
Create a scroll back to top button

### ISSUE THREAD

**Issue by zugzwang03** [abhishek213-alb/CountdownTimer#86]
I want to create a scroll back to top button, which on pressing, will scroll to top page very smoothly.
Can I make this contribution under hacktoberfest'22?

**Comment by prabhat7k** [comment]
@abhishek213-alb can I work on this under hacktoberfest??

**Comment by zugzwang03** [comment]
But I created it to get self-assigned na 😢

**Comment by abhishek213-alb** [comment]
@prabhat7k check other issues ....
