### ISSUE TITLE
Adding Custom Countdown Designs

### ISSUE THREAD

**Issue by abhishek213-alb** [abhishek213-alb/CountdownTimer#9]
![image](https://user-images.githubusercontent.com/76660005/193506539-da5371cf-d206-4265-8ab7-1be19eaf291e.png)
Sample image you can use your own creativity

**Comment by pkaustubh401** [comment]
Hey @abhishek213-alb I would like to work on this issue, can you please elaborate on the issue and assign it to me.

**Comment by abhishek213-alb** [comment]
Assigned all the best

**Comment by pkaustubh401** [comment]
Can you brief me about the same, I have seen that you have created a timer with a certain background. Do you want the user to select custom background for the timer?

**Comment by abhishek213-alb** [comment]
Yes 
Add this feature by which user can select custom background....

**Comment by pkaustubh401** [comment]
Okay got it
